version: "3.8"
services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config/video:/opt/selenoid/video"
      - "$PWD/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui
    platform: linux/amd64
    network_mode: bridge
    links:
      - selenoid
    hostname: "selenoid.example.com"
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  video-recorder:
    container_name: selenoid-recorder
    image: selenoid/video-recorder:latest-release
    platform: linux/amd64

  chrome:
    image: sskorol/selenoid_chromium_vnc:100.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenoid
    environment:
      - HUB_HOST=selenoid
      - HUB_PORT=4444

  maven:
    container_name: java-maven
    build: .
    volumes:
      - './target/:/Carina-demo/target'
      - './reports/:/Carina-demo/reports'
    environment:
      SUITE_NAME: testsuite